<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "relax5datepicker"
 *
 * Auto generated by Extension Builder 2017-02-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'relax5datepicker',
	'description' => 'Date- and Timepicker from relax5 project. Includes Timepicker. Based in jquery datepicker.',
	'category' => 'relax5.7',
	'author' => 'Christoph Balogh',
	'author_email' => 'cb@lustige-informatik.at',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
    'version' => '8.7.2-rc80128',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);